### ISSUE TITLE
C3 todo

### ISSUE THREAD

**Issue by OfficialMelonz** [OfficialMelonz/Chatswood-Cubing-Club#3]
- [ ] Make puzzles manual page

- [ ] Make 3x3 puzzle tutorial on website

- [ ] Make 2x2 puzzle tutorial on website

- [ ] Put correct pictures in 'Meet the Team' page
